# Generated by Django 6.0.2 on 2026-03-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_post_category_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='weight lifting', error_messages={'unique': 'Diese Kategorie existiert bereits'}, max_length=255, unique=True),
        ),
    ]
